#spring:
#  zipkin:
#    base-url: http://10.0.0.28:9455
#  sleuth:
#    sampler:
#      percentage: 1.0


spring:
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.0.0.31:3306/jinbi_store_dev?useUnicode=true&autoReconnect=true&characterEncoding=utf8
    username: jinbi
    password: mariadb
    driver-class-name: com.mysql.jdbc.Driver
      
eureka:
  client:
    service-url:
      defaultZone: http://10.0.0.28:7001/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}   # 在信息列表时显示主机名称
    prefer-ip-address: true         # 访问的路径变为IP地址
    
